name: Bug Report
description: Let us know if something isn't working the way you expect.
title: "[bug]: "
labels:
  - bug
  - triage
assignees:
  - LoveGudu
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to let us know something isn't working as expected.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: input
    id: which-page
    attributes:
      label: Which page did this occur on?
      description: Please paste the address from the web browser.
      placeholder: ex. https://cps-innovation.github.io/digital-sop/playbooks/
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what has gone wrong.
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our 
        [Code of Conduct](https://github.com/CPS-Innovation/digital-sop/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
